#! /bin/bash

if [ ! -e ../1dwd_rigid_maps/1dwd_rigid.maps.fld ]; then
	echo making maps in 1dwd_rigid_maps
	autogrid4 -p 1dwd_rigid.gpf -l 1dwd_rigid.glg

	mv *.maps *.fld *.xyz ../1dwd_rigid_maps
fi
