
#ifndef CMDMODE
#define CMDMODE
#include "constants.h"
#include "set_cmd_io_std.h"
#include "print_2x.h"
#include "parse_com_line.h"
#include "strindex.h"
#include "print_avsfld.h"
#include "printEnergies.h"
#include "success.h"
#include "readPDBQ.h"
#include "get_atom_type.h"
#include "timesys.h"
#include "eintcal.h"
#include "trilinterp.h"
#include "qmultiply.h"
#include "cnv_state_to_coords.h"
#include "parse_trj_line.h"
#include "input_state.h"
#include "openfile.h"
int   cmdmode( int natom,
             Clock jobStart,
             struct tms tms_jobStart,
             FloatOrDouble xlo,
             FloatOrDouble ylo,
             FloatOrDouble zlo,
             FloatOrDouble xhi,
             FloatOrDouble yhi,
             FloatOrDouble zhi,
             FloatOrDouble inv_spacing,
             FloatOrDouble map[MAX_GRID_PTS][MAX_GRID_PTS][MAX_GRID_PTS][MAX_MAPS],
             FloatOrDouble e_internal[NEINT][ATOM_MAPS][ATOM_MAPS],
             FloatOrDouble WallEnergy,
             FloatOrDouble vt[MAX_TORS][SPACE],
             int   tlist[MAX_TORS][MAX_ATOMS],
             int   ntor,
             int   Nnb,
             int   nonbondlist[MAX_NONBONDS][2],
             char  atomstuff[MAX_ATOMS][MAX_CHARS],
             FloatOrDouble crdpdb[MAX_ATOMS][SPACE],
             char  hostnm[MAX_CHARS],
             int   type[MAX_ATOMS],
             FloatOrDouble charge[MAX_ATOMS],
	     Boole B_calcIntElec,
	     FloatOrDouble q1q2[MAX_NONBONDS],
	     char  atm_typ_str[ATOM_MAPS],
	     FloatOrDouble torsFreeEnergy,
       int ligand_is_inhibitor,
       FloatOrDouble map_center[SPACE]);
#endif
