#! /bin/bash
# $Id: configure-universalDarwin,v 1.1 2009/09/17 22:08:01 rhuey Exp $

# run configure (or ../configure) for universalDarwinNN

# required argument - in form universalDarwinNN   NN=8,9,10


ver=$1;shift

if [ t$ver = t ]; then
	echo "$0: usage: configure-universalDarwin NN"
	echo "  NN=8,9,10 or any string that ends with one of those."
	exit 1
fi

if [ -x configure ]; then
	config=configure
elif [ -x ../configure ]; then
	config=../configure
else
	echo $0 cannot find configure script
	exit 1
fi

case $ver in
  *8) 
	# Tiger (Intel/PPC; only 32-bit is supported here)
	archlist="-arch i386 -arch ppc"
	sdkver=4u
	;;
  *9) 
	# Leopard (Intel/PPC; 32/64-bit)
	archlist="-arch i386 -arch x86_64 -arch ppc -arch ppc64"
	sdkver=5
	;;
  *10) 
	# Snow Leopard (Intel 32/64-bit)
	archlist="-arch i386 -arch x86_64"
	sdkver=6
	;;
  *)
  	echo $0 unrecogized Darwin version $ver
	exit 1
	;;
esac

configopts="--disable-dependency-tracking"

rootdir=/Developer/SDKs/MacOSX10.$sdkver.sdk

if [ ! -d $rootdir ]; then
	echo Cannot find developer tool directory $rootdir
	echo "Please download \"Developer Tools\" from apple.com."
	exit 1
fi

env CXXFLAGS="-O3 -isysroot $rootdir $archlist" \
    LDFLAGS="$archlist" \
    $config $configopts

