#! /bin/bash
# $Id: configure_universal_Darwin8,v 1.1 2009/05/29 21:01:58 rhuey Exp $
archlist="-arch i386 -arch ppc"
env CXXFLAGS="-O3 -isysroot /Developer/SDKs/MacOSX10.4u.sdk $archlist" \
    LDFLAGS="$archlist" \
 ../configure --disable-dependency-tracking
