#! /bin/bash
# $Id: mkdistbins,v 1.4 2013/05/07 19:36:20 mp Exp $
distdir=/mgl/works/rhuey/autodocksuite-4.2.3
#archlist="sun4SunOS5 ia64Linux2 universalDarwin8 universalDarwin9"
archlist="i86Cygwin i86Linux2 x86_64Linux2 sun4SunOS5 ia64Linux2 universalDarwin8 universalDarwin9 universalDarwin10"
proglist="autodock autogrid"
version=4
umask 0

run=echo # debugging

for arch in $archlist; do
   archok=y

   case $arch in 
    i86Cygwin) exeext=.exe ;;
    *) exeext="";;
    esac
    
    case $arch in
    i86Cygwin) host=hao;; # dummy
    i86Linux2) host=enos;;   # 32-bit Intel Linux
    x86_64Linux2) host=saul;;   # 64-bit Intel Linux
    sun4SunOS5) host=riscfs2;;
    ia64Linux2) host=abraham;;
    universalDarwin9) host=esau;;   # 10.5 Leopard
    universalDarwin10) host=rapa;;  # 10.6 Snow Leopard
    universalDarwin11) host=ubl;;    # 10.7 Lion
    universalDarwin12) host=luna;;    # 10.8 Mountain Lion
    *) host=dummy;;
    esac

    for prog in autodock autogrid; do
       case $arch in
       *Darwin*) 
           case $prog in
              autodock) config_cmd="../configure-universalDarwin" ;;
              autogrid) config_cmd="../../autodock/configure-universalDarwin" ;;
           esac
           ;;
       *) config_cmd="../configure";;
       esac

        $run "umask 0; mkdir $distdir/$prog/$arch"
        # wish list:
        rcmd="umask 0;cd $distdir/$prog/$arch; $config_cmd; make; make test"
        $run ssh $host \"$rcmd\"
   done
done

