#! /bin/bash

( cd dock_rigidlig; bash make_rec_maps)
( cd dock_flexlig_flexres; bash make_rigid_maps)


for d in \
	eval_lig  \
	local_search_lig  \
	simulated_annealing \
	dock_rigidlig  \
	dock_flexlig  \
	dock_flexlig_flexres  \
	; do

	echo "$(date)  running examples in $d"
	( cd $d; bash run_examples )
done
