#! /bin/bash

( cd dock_rigidlig; bash make_rec_maps)
( cd dock_flexlig_flexres; bash make_rigid_maps)


for d in \
	eval_lig  \
	local_search_lig  \
	dock_rigidlig  \
	dock_flexlig  \
	dock_flexlig_flexres  \
	dock_flexlig_25M  \
	dock_flexlig_flexres_25M  \
	dock_rigidlig_25M  \
	; do

	echo running examples in $d
	( cd $d; bash run_examples )
done
